name: clang-format Check
on: 
  workflow_dispatch:
  push:
jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip-ci')"
    steps:
    - uses: actions/checkout@v2
    - name: Run clang-format style check for C programs.
      uses: DoozyX/clang-format-lint-action@v0.11
      with:
        source: '.'
        extensions: 'c,h,cpp,hpp'
        clangFormatVersion: 10
        inplace: True
        style: file
        # exclude: './config '
    - uses: EndBug/add-and-commit@v7
      with:
          author_name: github-actions
          author_email: github-actions[bot]@users.noreply.github.com
          message: 'Committing clang-format changes'
