name: h5bench (HDF5 develop) 

on:
  pull_request:

  workflow_dispatch:

jobs:
  h5bench:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install cmake gcc libtool zlib1g-dev python3 libopenmpi-dev -y
          
          # HDF5
          git clone https://github.com/HDFGroup/hdf5.git

          # VOL-ASYNC
          git clone --recursive https://github.com/hpc-io/vol-async.git

      - name: Build HDF5 develop
        run: |
          export HDF5_DIR=/opt/hdf5
          export HDF5_LIBTOOL=/usr/bin/libtoolize
          
          mkdir $HDF5_DIR

          cd hdf5

          ./autogen.sh
          ./configure --prefix=$HDF5_DIR --enable-parallel --enable-threadsafe --enable-unsupported

          make -j 8
          make install

      - name: Build Argobots
        run: |
          current="$PWD"

          export ABT_DIR=$current/vol-async/argobots
          
          cd $ABT_DIR

          ./autogen.sh
          ./configure --prefix=$ABT_DIR/install

          make -j 8
          make install

      - name: Build VOL-ASYNC
        run: |
          current="$PWD"

          export HDF5_DIR=/opt/hdf5
          export ABT_DIR=$current/vol-async/argobots/install
          export VOL_DIR=$current/vol-async
          
          cd $VOL_DIR
          cd src
          tail -n 48 Makefile.summit > Makefile
          make

      - name: Build VOL-ASYNC Tests
        run: |
          current="$PWD"

          export HDF5_DIR=/opt/hdf5
          export ABT_DIR=$current/vol-async/argobots/install
          export VOL_DIR=$current/vol-async
          export ASYNC_DIR=$current/vol-async/src

          export LD_LIBRARY_PATH=$VOL_DIR/src:$HDF5_DIR/lib:$ABT_DIR/lib:$LD_LIBRARY_PATH
          export HDF5_PLUGIN_PATH="$VOL_DIR/src"
          export HDF5_VOL_CONNECTOR="async under_vol=0;under_info={}"

          cd $VOL_DIR/test
          tail -n 47 Makefile.summit > Makefile
          export LD_PRELOAD=$ABT_DIR/lib/libabt.so
          make -j 8

      - name: Test VOL-ASYNC
        run: |
          current="$PWD"

          cd $current/vol-async/test
          
          export HDF5_DIR=/opt/hdf5
          export ABT_DIR=$current/vol-async/argobots/install
          export VOL_DIR=$current/vol-async

          export LD_LIBRARY_PATH=$VOL_DIR/src:$HDF5_DIR/lib:$ABT_DIR/lib:$LD_LIBRARY_PATH
          export HDF5_PLUGIN_PATH="$VOL_DIR/src"
          export HDF5_VOL_CONNECTOR="async under_vol=0;under_info={}"
          
          make check

      - name: Build h5bench SYNC
        run: |
          current="$PWD"
          export HDF5_HOME=/opt/hdf5

          mkdir build-sync
          cd build-sync

          cmake .. -DCMAKE_C_COMPILER=$HDF5_HOME/bin/h5pcc
          make

      - name: Build h5bench ASYNC
        run: |
          current="$PWD"

          export HDF5_HOME=/opt/hdf5
          export ASYNC_HOME=$current/vol-async/src
          
          mkdir build-async
          cd build-async

          cmake .. \
            -DWITH_ASYNC_VOL:BOOL=ON \
            -DCMAKE_C_FLAGS="-I/$current/vol-async/src -L/$current/vol-async/src" \
            -DCMAKE_C_COMPILER=$HDF5_HOME/bin/h5pcc
          make

      - name: Test h5bench SYNC write/read
        run: |
          cd build-sync
          ./h5bench --debug --abort-on-failure --validate-mode ../samples/sync-write-read-contig-1d-small.json

      - name: Test h5bench SYNC write 1D contiguous (memory) strided (file)
        run: |
          cd build-sync
          ./h5bench --debug --abort-on-failure --validate-mode ../samples/sync-write-1d-contig-strided.json

      - name: Test h5bench SYNC write 1D contiguous (memory) contiguous (file)
        run: |
          cd build-sync
          ./h5bench --debug --abort-on-failure --validate-mode ../samples/sync-write-1d-contig-contig.json

      - name: Test h5bench SYNC write 1D contiguous (memory) interleaved (file)
        run: |
          cd build-sync
          ./h5bench --debug --abort-on-failure --validate-mode ../samples/sync-write-1d-contig-interleaved.json

      - name: Test h5bench SYNC write 1D interleaved (memory) contiguous (file)
        run: |
          cd build-sync
          ./h5bench --debug --abort-on-failure --validate-mode ../samples/sync-write-1d-interleaved-contig.json

      - name: Test h5bench SYNC write 1D interleaved (memory) interleaved (file)
        run: |
          cd build-sync
          ./h5bench --debug --abort-on-failure --validate-mode ../samples/sync-write-1d-interleaved-interleaved.json

      - name: Test h5bench SYNC write 2D contiguous (memory) contiguous (file)
        run: |
          cd build-sync
          ./h5bench --debug --abort-on-failure --validate-mode ../samples/sync-write-2d-contig-contig.json

      - name: Test h5bench SYNC write 2D contiguous (memory) interleaved (file)
        run: |
          cd build-sync
          ./h5bench --debug --abort-on-failure --validate-mode ../samples/sync-write-2d-contig-interleaved.json

      - name: Test h5bench SYNC write 2D interleaved (memory) contiguous (file)
        run: |
          cd build-sync
          ./h5bench --debug --abort-on-failure --validate-mode ../samples/sync-write-2d-interleaved-contig.json

      - name: Test h5bench SYNC write 2D interleaved (memory) interleaved (file)
        run: |
          cd build-sync
          ./h5bench --debug --abort-on-failure --validate-mode ../samples/sync-write-2d-interleaved-interleaved.json

      - name: Test h5bench SYNC write 3D contiguous (memory) contiguous (file)
        run: |
          cd build-sync
          ./h5bench --debug --abort-on-failure --validate-mode ../samples/sync-write-3d-contig-contig.json

      - name: Test h5bench SYNC write unlimited
        run: |
          cd build-sync
          ./h5bench --debug --abort-on-failure ../samples/sync-write-unlimited.json

      - name: Test h5bench SYNC overwrite
        run: |
          cd build-sync
          ./h5bench --debug --abort-on-failure ../samples/sync-overwrite.json

      - name: Test h5bench SYNC append
        run: |
          cd build-sync
          ./h5bench --debug --abort-on-failure ../samples/sync-append.json

      - name: Test h5bench SYNC exerciser
        run: |
          cd build-sync
          ./h5bench --debug --abort-on-failure ../samples/sync-exerciser.json

      - name: Test h5bench SYNC metadata
        run: |
          cd build-sync
          ./h5bench --debug --abort-on-failure ../samples/sync-metadata.json

      - name: Test h5bench SYNC amrex
        run: |
          cd build-sync
          ./h5bench --debug --abort-on-failure ../samples/sync-amrex.json

      - name: Test h5bench SYNC openpmd
        run: |
          cd build-sync
          ./h5bench --debug --abort-on-failure ../samples/sync-openpmd.json

      - name: Test h5bench ASYNC write/read
        run: |
          current="$PWD"

          export HDF5_DIR=/opt/hdf5
          export ABT_DIR=$current/vol-async/argobots/install
          export VOL_DIR=$current/vol-async
          export ASYNC_DIR=$VOL_DIR/src

          export LD_PRELOAD=$ABT_DIR/lib/libabt.so

          cd build-async

          python3 ../samples/update.py ../samples/async-write-read-contig-1d-small.json

          ./h5bench --debug --abort-on-failure ../samples/async-write-read-contig-1d-small.json

      - name: Test h5bench ASYNC write 1D contiguous (memory) strided (file)
        run: |
          current="$PWD"

          export HDF5_DIR=/opt/hdf5
          export ABT_DIR=$current/vol-async/argobots/install
          export VOL_DIR=$current/vol-async
          export ASYNC_DIR=$VOL_DIR/src
          
          export LD_PRELOAD=$ABT_DIR/lib/libabt.so

          cd build-async

          python3 ../samples/update.py ../samples/async-write-1d-contig-strided.json

          ./h5bench --debug --abort-on-failure --validate-mode ../samples/async-write-1d-contig-strided.json

      - name: Test h5bench ASYNC write 1D contiguous (memory) contiguous (file)
        run: |
          current="$PWD"

          export HDF5_DIR=/opt/hdf5
          export ABT_DIR=$current/vol-async/argobots/install
          export VOL_DIR=$current/vol-async
          export ASYNC_DIR=$VOL_DIR/src
          
          export LD_PRELOAD=$ABT_DIR/lib/libabt.so

          cd build-async

          python3 ../samples/update.py ../samples/async-write-1d-contig-contig.json

          ./h5bench --debug --abort-on-failure --validate-mode ../samples/async-write-1d-contig-contig.json

      - name: Test h5bench ASYNC write 1D contiguous (memory) interleaved (file)
        run: |
          current="$PWD"

          export HDF5_DIR=/opt/hdf5
          export ABT_DIR=$current/vol-async/argobots/install
          export VOL_DIR=$current/vol-async
          export ASYNC_DIR=$VOL_DIR/src
          
          export LD_PRELOAD=$ABT_DIR/lib/libabt.so

          cd build-async

          python3 ../samples/update.py ../samples/async-write-1d-contig-interleaved.json

          ./h5bench --debug --abort-on-failure --validate-mode ../samples/async-write-1d-contig-interleaved.json

      - name: Test h5bench ASYNC write 1D interleaved (memory) contiguous (file)
        run: |
          current="$PWD"

          export HDF5_DIR=/opt/hdf5
          export ABT_DIR=$current/vol-async/argobots/install
          export VOL_DIR=$current/vol-async
          export ASYNC_DIR=$VOL_DIR/src
          
          export LD_PRELOAD=$ABT_DIR/lib/libabt.so

          cd build-async

          python3 ../samples/update.py ../samples/async-write-1d-interleaved-contig.json

          ./h5bench --debug --abort-on-failure --validate-mode ../samples/async-write-1d-interleaved-contig.json

      - name: Test h5bench ASYNC write 1D interleaved (memory) interleaved (file)
        run: |
          current="$PWD"

          export HDF5_DIR=/opt/hdf5
          export ABT_DIR=$current/vol-async/argobots/install
          export VOL_DIR=$current/vol-async
          export ASYNC_DIR=$VOL_DIR/src
          
          export LD_PRELOAD=$ABT_DIR/lib/libabt.so

          cd build-async

          python3 ../samples/update.py ../samples/async-write-1d-interleaved-interleaved.json

          ./h5bench --debug --abort-on-failure --validate-mode ../samples/async-write-1d-interleaved-interleaved.json

      - name: Test h5bench ASYNC write 2D contiguous (memory) contiguous (file)
        run: |
          current="$PWD"

          export HDF5_DIR=/opt/hdf5
          export ABT_DIR=$current/vol-async/argobots/install
          export VOL_DIR=$current/vol-async
          export ASYNC_DIR=$VOL_DIR/src
          
          export LD_PRELOAD=$ABT_DIR/lib/libabt.so

          cd build-async

          python3 ../samples/update.py ../samples/async-write-2d-contig-contig.json

          ./h5bench --debug --abort-on-failure --validate-mode ../samples/async-write-2d-contig-contig.json

      - name: Test h5bench ASYNC write 2D contiguous (memory) interleaved (file)
        run: |
          current="$PWD"

          export HDF5_DIR=/opt/hdf5
          export ABT_DIR=$current/vol-async/argobots/install
          export VOL_DIR=$current/vol-async
          export ASYNC_DIR=$VOL_DIR/src
          
          export LD_PRELOAD=$ABT_DIR/lib/libabt.so

          cd build-async

          python3 ../samples/update.py ../samples/async-write-2d-contig-interleaved.json

          ./h5bench --debug --abort-on-failure --validate-mode ../samples/async-write-2d-contig-interleaved.json

      - name: Test h5bench ASYNC write 2D interleaved (memory) contiguous (file)
        run: |
          current="$PWD"

          export HDF5_DIR=/opt/hdf5
          export ABT_DIR=$current/vol-async/argobots/install
          export VOL_DIR=$current/vol-async
          export ASYNC_DIR=$VOL_DIR/src
          
          export LD_PRELOAD=$ABT_DIR/lib/libabt.so

          cd build-async

          python3 ../samples/update.py ../samples/async-write-2d-interleaved-contig.json

          ./h5bench --debug --abort-on-failure --validate-mode ../samples/async-write-2d-interleaved-contig.json

      - name: Test h5bench ASYNC write 2D interleaved (memory) interleaved (file)
        run: |
          current="$PWD"

          export HDF5_DIR=/opt/hdf5
          export ABT_DIR=$current/vol-async/argobots/install
          export VOL_DIR=$current/vol-async
          export ASYNC_DIR=$VOL_DIR/src
          
          export LD_PRELOAD=$ABT_DIR/lib/libabt.so

          cd build-async

          python3 ../samples/update.py ../samples/async-write-2d-interleaved-interleaved.json

          ./h5bench --debug --abort-on-failure --validate-mode ../samples/async-write-2d-interleaved-interleaved.json

      - name: Test h5bench ASYNC write 3D contiguous (memory) contiguous (file)
        run: |
          current="$PWD"

          export HDF5_DIR=/opt/hdf5
          export ABT_DIR=$current/vol-async/argobots/install
          export VOL_DIR=$current/vol-async
          export ASYNC_DIR=$VOL_DIR/src
          
          export LD_PRELOAD=$ABT_DIR/lib/libabt.so

          cd build-async

          python3 ../samples/update.py ../samples/async-write-3d-contig-contig.json

          ./h5bench --debug --abort-on-failure --validate-mode ../samples/async-write-3d-contig-contig.json

      - name: Test h5bench ASYNC amrex
        run: |
          current="$PWD"

          export HDF5_DIR=/opt/hdf5
          export ABT_DIR=$current/vol-async/argobots/install
          export VOL_DIR=$current/vol-async
          export ASYNC_DIR=$VOL_DIR/src

          export LD_PRELOAD=$ABT_DIR/lib/libabt.so

          cd build-async

          python3 ../samples/update.py ../samples/async-amrex.json

          ./h5bench --debug --abort-on-failure ../samples/async-amrex.json

      - name: Upload artifact
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test
          path: build*/storage/**/std*
          retention-days: 1
