name: h5bench (HDF5 1.12.0)

on:
  pull_request:

  workflow_dispatch:

jobs:
  h5bench:
    runs-on: ubuntu-20.04
    container:
      image: jlbez/hdf5-1.12.0
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true

      - name: Build h5bench
        run: |
          export HDF5_HOME=/opt/hdf5
          mkdir build
          cd build
          CC=mpicc cmake ..
          make -j 8
          
      - name: Test h5bench SYNC write/read
        run: |
          cd build
          ./h5bench --debug --abort-on-failure ../samples/sync-write-read-contig-1d-small.json

      - name: Test h5bench SYNC exerciser
        run: |
          cd build
          ./h5bench --debug --abort-on-failure ../samples/sync-exerciser.json

      - name: Test h5bench SYNC metadata
        run: |
          cd build
          ./h5bench --debug --abort-on-failure ../samples/sync-metadata.json

      - name: Upload artifact
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test
          path: build/storage/**/std*
          retention-days: 1