name: h5bench (HDF5 1.12.0)

on:
  pull_request:

  workflow_dispatch:

jobs:
  h5bench:
    runs-on: ubuntu-20.04
    container:
      image: hpcio/hdf5-1.12.0
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true

      - name: Dependencies
        run: |
          # PnetCDF
          wget https://parallel-netcdf.github.io/Release/pnetcdf-1.12.2.tar.gz
          tar -zxf pnetcdf-1.12.2.tar.gz
          mv pnetcdf-1.12.2 pnetcdf

      - name: Build PnetCDF
        run: |
          export HDF5_DIR=/opt/hdf5
          export PNETCDF_DIR=/opt/pnetcdf

          cd pnetcdf

          ./configure --prefix=${PNETCDF_DIR} CC=mpicc

          make -j 8
          make install

      - name: Build h5bench
        run: |
          export HDF5_HOME=/opt/hdf5
          export PNETCDF_HOME=/opt/pnetcdf

          mkdir build
          cd build
          CC=mpicc cmake ..
          make -j 8
          
      - name: Test h5bench SYNC write/read
        run: |
          cd build
          ./h5bench --debug --abort-on-failure --validate-mode ../samples/sync-write-read-contig-1d-small.json

      - name: Test h5bench SYNC write 1D contiguous (memory) strided (file)
        run: |
          cd build
          ./h5bench --debug --abort-on-failure --validate-mode ../samples/sync-write-1d-contig-strided.json

      - name: Test h5bench SYNC write 1D contiguous (memory) contiguous (file)
        run: |
          cd build
          ./h5bench --debug --abort-on-failure --validate-mode ../samples/sync-write-1d-contig-contig.json

      - name: Test h5bench SYNC write 1D contiguous (memory) interleaved (file)
        run: |
          cd build
          ./h5bench --debug --abort-on-failure --validate-mode ../samples/sync-write-1d-contig-interleaved.json

      - name: Test h5bench SYNC write 1D interleaved (memory) contiguous (file)
        run: |
          cd build
          ./h5bench --debug --abort-on-failure --validate-mode ../samples/sync-write-1d-interleaved-contig.json

      - name: Test h5bench SYNC write 1D interleaved (memory) interleaved (file)
        run: |
          cd build
          ./h5bench --debug --abort-on-failure --validate-mode ../samples/sync-write-1d-interleaved-interleaved.json

      - name: Test h5bench SYNC write 2D contiguous (memory) contiguous (file)
        run: |
          cd build
          ./h5bench --debug --abort-on-failure --validate-mode ../samples/sync-write-2d-contig-contig.json

      - name: Test h5bench SYNC write 2D contiguous (memory) interleaved (file)
        run: |
          cd build
          ./h5bench --debug --abort-on-failure --validate-mode ../samples/sync-write-2d-contig-interleaved.json

      - name: Test h5bench SYNC write 2D interleaved (memory) contiguous (file)
        run: |
          cd build
          ./h5bench --debug --abort-on-failure --validate-mode ../samples/sync-write-2d-interleaved-contig.json

      - name: Test h5bench SYNC write 2D interleaved (memory) interleaved (file)
        run: |
          cd build
          ./h5bench --debug --abort-on-failure --validate-mode ../samples/sync-write-2d-interleaved-interleaved.json

      - name: Test h5bench SYNC write 3D contiguous (memory) contiguous (file)
        run: |
          cd build
          ./h5bench --debug --abort-on-failure --validate-mode ../samples/sync-write-3d-contig-contig.json

      - name: Test h5bench SYNC read 1D contiguous (memory) contiguous (file) full
        run: |
          cd build
          ./h5bench --debug --abort-on-failure --validate-mode ../samples/sync-write-1d-contig-contig-read-full.json

      - name: Test h5bench SYNC read 1D contiguous (memory) contiguous (file) partial
        run: |
          cd build
          ./h5bench --debug --abort-on-failure --validate-mode ../samples/sync-write-1d-contig-contig-read-partial.json

      - name: Test h5bench SYNC read 1D contiguous (memory) contiguous (file) strided
        run: |
          cd build
          ./h5bench --debug --abort-on-failure --validate-mode ../samples/sync-write-1d-contig-contig-read-strided.json

      - name: Test h5bench SYNC read 2D contiguous (memory) contiguous (file) full
        run: |
          cd build
          ./h5bench --debug --abort-on-failure --validate-mode ../samples/sync-write-2d-contig-contig-read-full.json

      - name: Test h5bench SYNC read 3D contiguous (memory) contiguous (file) full
        run: |
          cd build
          ./h5bench --debug --abort-on-failure --validate-mode ../samples/sync-write-2d-contig-contig-read-full.json

      - name: Test h5bench SYNC read 1D contiguous (memory) contiguous (file) full
        run: |
          cd build
          ./h5bench --debug --abort-on-failure --validate-mode ../samples/sync-write-1d-contig-contig-read-full.json

      - name: Test h5bench SYNC read 1D contiguous (memory) contiguous (file) partial
        run: |
          cd build
          ./h5bench --debug --abort-on-failure --validate-mode ../samples/sync-write-1d-contig-contig-read-partial.json

      - name: Test h5bench SYNC read 1D contiguous (memory) contiguous (file) strided
        run: |
          cd build
          ./h5bench --debug --abort-on-failure --validate-mode ../samples/sync-write-1d-contig-contig-read-strided.json

      - name: Test h5bench SYNC read 2D contiguous (memory) contiguous (file) full
        run: |
          cd build
          ./h5bench --debug --abort-on-failure --validate-mode ../samples/sync-write-2d-contig-contig-read-full.json

      - name: Test h5bench SYNC read 3D contiguous (memory) contiguous (file) full
        run: |
          cd build
          ./h5bench --debug --abort-on-failure --validate-mode ../samples/sync-write-2d-contig-contig-read-full.json

      - name: Test h5bench SYNC write unlimited
        run: |
          cd build
          ./h5bench --debug --abort-on-failure ../samples/sync-write-unlimited.json

      - name: Test h5bench SYNC overwrite
        run: |
          cd build
          ./h5bench --debug --abort-on-failure ../samples/sync-overwrite.json

      - name: Test h5bench SYNC append
        run: |
          cd build
          ./h5bench --debug --abort-on-failure ../samples/sync-append.json

      - name: Test h5bench SYNC exerciser
        run: |
          cd build
          ./h5bench --debug --abort-on-failure ../samples/sync-exerciser.json

      - name: Test h5bench SYNC metadata
        run: |
          cd build
          ./h5bench --debug --abort-on-failure ../samples/sync-metadata.json

      - name: Test h5bench SYNC amrex
        run: |
          cd build
          ./h5bench --debug --abort-on-failure ../samples/sync-amrex.json

      - name: Test h5bench SYNC openpmd
        run: |
          cd build
          ./h5bench --debug --abort-on-failure ../samples/sync-openpmd.json

      - name: Test h5bench SYNC e3sm
        run: |
          export LD_LIBRARY_PATH=/opt/hdf5/lib:$LD_LIBRARY_PATH

          cd build
          ./h5bench --debug --abort-on-failure ../samples/sync-e3sm.json

      - name: Upload artifact
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test
          path: build/storage/**/std*
          retention-days: 1
